/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.bolton.oom.view.panel;

import uk.bolton.oom.view.UserPage;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;

/**
 *
 * @author Binura
 */
public class UserStartPanel extends JPanel {

    private javax.swing.JLabel btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWarning;
    private JPanel pnlMain;
    private javax.swing.JTextField txtUserlName;

    /**
     * Creates new form ChannelStartPanel
     */
    
    private UserPage userMainJFrame;
    
    public UserStartPanel(UserPage userMainJFrame) {
        this.userMainJFrame = userMainJFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JLabel();
        txtUserlName = new javax.swing.JTextField();
        lblWarning = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1105, 800));

        pnlMain.setBackground(new Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1105, 800));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Let's start with a name for your account");

        btnNext.setBackground(new Color(59, 89, 152));
        btnNext.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        btnNext.setForeground(new Color(255, 255, 255));
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNext.setText("Next");
        btnNext.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(59, 89, 152)));
        btnNext.setOpaque(true);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        txtUserlName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtUserlName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserlName.setToolTipText("Enter your user name");
        txtUserlName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserlNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserlNameFocusLost(evt);
            }
        });
        txtUserlName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserlNameActionPerformed(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWarning.setForeground(new Color(255, 255, 255));
        lblWarning.setText("Please provide a valid user name");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317))))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserlName, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 137, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(txtUserlName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMain.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserlNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserlNameFocusGained
        // TODO add your handling code he if (searchText.getText().equals("Search")) {

    }//GEN-LAST:event_txtUserlNameFocusGained

    private void txtUserlNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserlNameFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtUserlNameFocusLost

    private void txtUserlNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserlNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserlNameActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        if (isValidateUserName()) {
      
            String userName = txtUserlName.getText();
            loadNewPanelToContainterPanel(new UserContentPanel(userName));
        }
    }//GEN-LAST:event_btnNextMouseClicked


    

    private void loadNewPanelToContainterPanel(JPanel newPanel) {
        newPanel.setSize(userMainJFrame.getContainerPanel().getSize());
        userMainJFrame.getContainerPanel().removeAll();
        userMainJFrame.getContainerPanel().add(newPanel);
        userMainJFrame.getContainerPanel().revalidate();
        userMainJFrame.getContainerPanel().repaint();
        newPanel.setVisible(true);
    }

    private Boolean isValidateUserName() {
        if (txtUserlName.getText().isEmpty()) {
            txtUserlName.setBorder(new LineBorder(Color.RED, 2));
            lblWarning.setForeground(Color.red);
            return false;
        }
        return true;
    }

}
